### PR TITLE
Changes made in order to make compilation possible and runtime proper

### PR DESCRIPTION
**Pull request by LeviTaule**
When trying to compile and run the game, I needed to make these changes to make compilation possible, runtime proper (e.g. able to get resources), and comitting easier :)

 * In `std::sort()`, arguments in compare function need to be `const`.
 * Binary is now created in bin/ folder, where all the resource are located.
 * When comitting, git now automatically ignores files created by CMake (cross-platform and Linux ones.)

### CODE REVIEW

**Comment by LeviTaule** [comment]
So there's no author's intention in making it possible for linux guys to compile and run this game?

**Comment by MikkoFinell** [comment]
Hi. Can you explain what problems you were having? I have been compiling this under on Ubuntu 14.14 using compiler `gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1` without any issues so I would be interested to know your environment and exact errors.

Your changes are OK, thanks for contributing.

**Comment by LeviTaule** [comment]
Well, the problem with compiling was the `gcc` version. I was using `gcc 4.8.2`. It works just fine with `gcc 4.9.2`.
But that was just one problem. The second one is creating executable **outside** `bin/` directory - which means the font and the image can't be loaded. The third point is implicit ignoring the file created by CMake (so you don't have to do this explicitly or remove them each time you commit)

**Comment by MikkoFinell** [comment]
> The second one is creating executable outside bin/ directory - which means the font and the image can't be loaded.

Are you running the executable from outside `bin`? I don't know what the most standard practice is, but I was always running the build scrips and resuling executable from inside bin. Please explain how you do it.

**Comment by LeviTaule** [comment]
> I have been compiling this under on Ubuntu 14.10 using compiler gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1 without any issues so I would be interested to know about your environment, build process and exact errors.

I was compiling this using `gcc 4.8.2`. After installing `gcc 4.9.2` it works just fine.

> Are you running the executable from outside bin? I don't know what the most standard practice is, but I was always running the build scrips and resuling executable from inside bin.

First of all, I'm sorry, I removed the comment you were quoting - I post it without reading your updated comment. And yes, I'm always running compilation scripts from project root directory, never from `bin/`.  My bad I didn't consider different approaches.

All right, I'll update my branch to be consistent with your approach.

**Pull request closed without merging**
